add
HendrikNeuschulz/Capstone-Projekt pull request #4
Opened 2022-11-16 16:17 UTC by HendrikNeuschulz

2022-11-17 15:09 UTC, ahohnsen requested changes
Hey Hendrik,

I added some comments. Please have a look and if you have any questions, let me know 🙂

2022-11-17 15:09 UTC, ahohnsen commented on .storybook/preview.js
> +kaiserimport * as NextImage from "next/image";
🤔 
```suggestion
import * as NextImage from "next/image";
```

2022-11-17 15:09 UTC, ahohnsen commented on data.json
> +]
I would recommend you to keep your data uniform, e.g. the category is sometimes written with a capital letter and you mixed German and English. 🙈 

Is it on purpose that only the first item has the `pic` property? It also seems like you have added the path for the wrong picture as the dish name is "Pasta with Pesto" and the image file is called "bred.jpg" 🤔

2022-11-17 15:09 UTC, ahohnsen commented on pages/api/recipes/index.js
> +}
See my comment above

```suggestion
import { getAllDishes } from "../../../data/db";

export default async function handler(req, res) {
  if (req.method === "GET") {
    const dishes = await getAllDishes();
    res.status(200).json(dishes);
  } else {
    res.status(405).setHeader("Allow", ["GET"]).send();
  }
}
```

2022-11-17 15:09 UTC, ahohnsen commented on data/db.js
> +export { getAllEvents };
It is ok, if you take a few code lines from a previous project. However, you should always adjust it, so that it matches with your project. 
```suggestion
import dishes from "../data.json";

function getAllDishes() {
  return dishes;
}

export { getAllDishes };
```

2022-11-17 15:09 UTC, ahohnsen commented on pages/index.js
> +      <h3>my super tasty selection of recipes:</h3>
On a `h1` should always follow a `h2` 🙂.

2022-11-17 15:09 UTC, ahohnsen commented on pages/index.js
> +const recipeList = styled.ul``;
As these styled components are empty, they should be deleted 🧹 

Additionally, styled components have to start with a capital letter to be recognized as styled components.

```suggestion
```

2022-11-17 15:09 UTC, ahohnsen commented on pages/index.js
> +  const { data: data, error } = useSWR("/api/recipes", fetcher);
I would recommend to rename data to make it more descriptive. If you do so, do not forget to change it for this whole file 🙂 

```suggestion
  const { data: recipes, error } = useSWR("/api/recipes", fetcher);
```

2022-11-17 15:09 UTC, ahohnsen commented on pages/index.js
> +          <FoodCard />
You have to pass the data as a prop to your `FoodCard`, otherwise the data cannot be displayed.

```suggestion
        {recipes?.map((recipe) => (
          <FoodCard recipe={recipe}/>
```

2022-11-17 15:09 UTC, ahohnsen commented on components/FoodCard.js
> +}
In this component you receive data (line 7) but then you do not use it. Instead the image source is hard-coded, meaning that always the same image will be rendered.

```suggestion
export default function FoodCard({ recipe }) {
  return (
    <Card>
      <Image src={recipe.pic} width={200} alt={recipe.name} />
    </Card>
  );
}
```

2022-11-17 15:09 UTC, ahohnsen commented on components/FoodCard.js
> +import salmon from "../assets/images/salmon.jpg";
You do not need this import here. The image source is passed as a prop to this component (inside `data`).
```suggestion

```

2022-11-17 15:09 UTC, ahohnsen commented on components/FoodCard.js
> +import Link from "next/link";
I think you do not need to import the `Link` component as you do not use it in this file 🧹 

```suggestion

```

2022-11-17 15:09 UTC, ahohnsen commented on pages/index.js
> +    <>
We always want to have a `main` element, so I would use that one here instead.
```suggestion
    <main>
```

2022-11-18 10:13 UTC, mpagels requested changes
Found just one litte thing. Pls reveiw.

2022-11-18 10:13 UTC, mpagels commented on pages/index.js
> +          <FoodCard recipe={recipe} />
Be aware. You're missing the key prop here.

2022-11-18 11:00 UTC, mpagels requested changes
Check the key prop again. Might be an issue.

2022-11-18 11:00 UTC, mpagels commented on pages/index.js
> +          <FoodCard recipe={recipe} key={recipes.id} />
`recepies.id` could be a problem (the plural form) try the passed `recipe` value ;-)

2022-11-18 11:07 UTC, mpagels approved these changes
lgtm!

2022-11-18 15:14 UTC, Kheirah commented on pages/index.js
> +
You could add the case for when recipes is empty or otherwise unavailable, and return some JSX that says something like "data is loading ...".

2022-11-18 15:34 UTC, merged